version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    restart: unless-stopped
    container_name: leif-portfolio


  functions:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./netlify/functions:/app
      - ./package.json:/app/package.json:ro
    ports:
      - "9999:9999"
    environment:
      - HF_API_TOKEN=${HF_API_TOKEN}
    command: >
      sh -c "
        npm install netlify-lambda express cors &&
        npx netlify-lambda serve . --port 9999
      "
    container_name: portfolio-functions
    profiles:
      - functions
